### PR TITLE
Fix loop in timestamp

### PR DESCRIPTION
**Pull request by fredericgermain**
I found the timestamp loop with my device, a standard cc2531emk...

And here is the fix.

### CODE REVIEW

**Review by homewsn — COMMENTED** [review]
To be honest, I didn’t understand the point of replacing le32toh with le64toh. le_timestamp has a uint32 dimension, and lenntoh-like conversions on little-endian processors essentially return the original value. How can this help you?

**Comment by fredericgermain** [comment]
Screenshot from 2024-06-21 13-54-30

Isn't it a 64bit counter, as written in the spec and on line 142?

**Comment by fredericgermain** [comment]
```
Timestamp:
64 bit counter value. To calculate the time in microseconds this value must be divided by a number
depending on the clock speed used to drive the counter tics on the target. (E.g. CC243xEM, CC253x ->
32, CCxx10EM -> 26, SmartRF05EB + CC2520EM -> 24). The timestamp on the first packet will be
used as offset value for all packets. That means that packet number 1 will be shown in the packet
sniffer with time = 0.
```

If we consider this a 32 bits counter, with the current definition, we have a loop every ~134s (`(1<<32) / 32 / 1000 /1000`), which is what I think I saw in wireshark. Maybe I misunderstand something somewhere, I didn't spend much time on it, it just fixed my issue.

**Comment by homewsn** [comment]
You specified the packaging format in the PSD file. The format of USB packets is not described anywhere in the official documentation and is the result of research by third parties.
At least two types of packets are used: data (with a 32-bit time offset) and 32-bit ticks. The timestamp of a packet is their sum. There is a possibility of overflow, but only in special cases, see [discussion](https://github.com/homewsn/whsniff/issues/9).

**Comment by fredericgermain** [comment]
I've tested again, and indeed it works fine without my commit.
I really thought I saw a loop at some point.
Sorry about that.

**Pull request closed without merging**
